version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - nominatim
      - osrm
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=mapping
    volumes:    
      - .:/app  
      - /app/node_modules


  db:
    image: kartoza/postgis:14
    environment:
      POSTGRES_DB: mapping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  nominatim:
    image: mediagis/nominatim:3.7
    environment:
      NOMINATIM_EMAIL: "youremail422@gmail.com"
      PBF_URL: "http://download.geofabrik.de/asia/bangladesh-latest.osm.pbf"
    ports:
      - "8080:8080"

  osrm-prepare:
    image: osrm/osrm-backend:v5.24.0
    volumes:
      - ./data/osm:/data/osm
    command: >
      sh -c "
        osrm-extract -p /opt/car.lua /data/osm/map.osm.pbf &&
        osrm-partition /data/osm/map.osrm &&
        osrm-customize /data/osm/map.osrm
      "
    depends_on:
      - db
    deploy:
      replicas: 1

  osrm:
    image: osrm/osrm-backend:v5.24.0
    command: osrm-routed --algorithm mld /data/osm/map.osrm
    volumes:
      - ./data/osm:/data/osm
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
